import { Inter, Open_Sans } from "next/font/google";
import "../styles/globals/reset.scss";
import Navbar from "@/components/Navbar/Navbar";

const inter = Open_Sans({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
